MODEL (
    name openbca_input.measures,
    kind FULL,
);

SELECT
    CAST(unique_row_id AS STRING) AS unique_row_id,
    CAST(measure_id AS STRING) AS measure_id,
    CAST(project_id AS STRING) AS project_id,
    CAST(program_name AS STRING) AS program_name,
    CAST(measure_include AS STRING) AS measure_include,
    CAST(version AS STRING) AS version,
    CAST(avoided_cost_subset AS STRING) AS avoided_cost_subset,
    CAST(start_year AS INT) AS start_year,
    CAST(start_quarter AS INT) AS start_quarter,
    CAST(discount_rate AS FLOAT) AS discount_rate, 
    CAST(measure_name AS STRING) AS measure_name,
    CAST(measure_unit AS STRING) AS measure_unit,
    CAST(unit_quantity AS FLOAT) AS unit_quantity,
    CAST(electric_load_shape AS STRING) AS electric_load_shape,
    CAST(annual_kwh_savings AS FLOAT) AS annual_kwh_savings,
    CAST(coincident_peak_kw_savings AS FLOAT) AS coincident_peak_kw_savings,
    CAST(natural_gas_load_shape AS STRING) AS natural_gas_load_shape,
    CAST(annual_natural_gas_savings_mmbtu as FLOAT) AS annual_natural_gas_mmbtu_savings,
    CAST(annual_propane_savings_mmbtu as FLOAT) AS annual_propane_mmbtu_savings,
    CAST(annual_oil_savings_mmbtu as FLOAT) AS annual_oil_mmbtu_savings,
    CAST(annual_diesel_savings_mmbtu as FLOAT) AS annual_diesel_mmbtu_savings,
    CAST(estimated_useful_life_years AS INT) AS estimated_useful_life,
    CAST(ntg AS FLOAT) AS ntg,
    CAST(incremental_costs_upfront_per_unit_dollar AS FLOAT) AS incremental_costs_upfront_per_unit_dollar,
    CAST(annual_o_m_cost_per_unit_dollar_per_year AS FLOAT) AS annual_o_m_cost_per_unit_dollar_per_year,
    CAST(utility_upfront_incentive_per_unit_dollar AS FLOAT) AS utility_upfront_incentive_per_unit_dollar,
    CAST(utility_annual_incentive_per_unit_dollar_per_year AS FLOAT) AS utility_annual_incentive_per_unit_dollar_per_year,
    CAST(administration_costs_per_unit_dollar AS FLOAT) AS administration_costs_per_unit_dollar,
    CAST(host_customer_transaction_costs_per_unit_dollar AS FLOAT) AS host_customer_transaction_costs_per_unit_dollar,
    CAST(host_customer_interconnection_costs_per_unit_dollar AS FLOAT) AS host_customer_interconnection_costs_per_unit_dollar,
    CAST(host_customer_tax_incentives_per_unit_dollar AS FLOAT) AS host_customer_tax_incentives_per_unit_dollar,
    CAST(host_customer_non_energy_impacts_per_unit_dollar AS FLOAT) AS host_customer_non_energy_impacts_per_unit_dollar,
    CAST(host_customer_non_energy_impacts_low_income_per_unit_dollar AS FLOAT) AS host_customer_non_energy_impacts_low_income_per_unit_dollar,
    CAST(change_in_host_customer_reliability_per_unit AS FLOAT) AS change_in_host_customer_reliability_per_unit,
    CAST(change_in_host_customer_resilience_per_unit AS FLOAT) AS change_in_host_customer_resilience_per_unit,
    CAST(change_in_societal_resilience_per_unit AS FLOAT) AS change_in_societal_resilience_per_unit,
    CAST(custom_1_value_stream_name AS STRING) AS custom_1_value_stream_name,
    CAST(custom_1_value_stream_commodity AS STRING) AS custom_1_value_stream_commodity,
    CAST(custom_1_annual_savings AS FLOAT) AS custom_1_annual_savings, 
    CAST(custom_2_value_stream_name AS STRING) AS custom_2_value_stream_name,
    CAST(custom_2_value_stream_commodity AS STRING) AS custom_2_value_stream_commodity,
    CAST(custom_2_annual_savings AS FLOAT) AS custom_2_annual_savings, 
    CAST(custom_3_value_stream_name AS STRING) AS custom_3_value_stream_name,
    CAST(custom_3_value_stream_commodity AS STRING) AS custom_3_value_stream_commodity,
    CAST(custom_3_annual_savings AS FLOAT) AS custom_3_annual_savings, 
    CAST(custom_4_value_stream_name AS STRING) AS custom_4_value_stream_name,
    CAST(custom_4_value_stream_commodity AS STRING) AS custom_4_value_stream_commodity,
    CAST(custom_4_annual_savings AS FLOAT) AS custom_4_annual_savings, 
    CAST(custom_5_value_stream_name AS STRING) AS custom_5_value_stream_name,
    CAST(custom_5_value_stream_commodity AS STRING) AS custom_5_value_stream_commodity,
    CAST(custom_5_annual_savings AS FLOAT) AS custom_5_annual_savings, 
    CAST(label_1 AS STRING) AS label_1,    
    CAST(label_2 AS STRING) AS label_2,
    CAST(label_3 AS STRING) AS label_3,
    CAST(label_4 AS STRING) AS label_4,
    CAST(label_5 AS STRING) AS label_5,
FROM nspm.openbca_input_measures
