gateways:
  test_real_data_calculations_aggregated:
    connection:
      type: duckdb
      database: tests/test_real_data_calculations_aggregated/duckdb.db
  bigquery:
    connection:
      type: bigquery
      project: oeem-dev-loic

default_gateway: test_real_data_calculations_aggregated

model_defaults:
  dialect: duckdb
  start: 2025-04-01
