[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "open-bca"
version = "0.0.0"
description = "Open BCA project"
authors = [
  { name = "Open BCA" }
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
  "sqlmesh[web]==0.225.0",
  "duckdb==1.2.1",
  "matplotlib",
  "numpy",
  "pandas",
  "pytest==8.3.5",
  "streamlit",
  "altair",
  "watchdog",
  "openpyxl",
  "tabulate>=0.9.0",
  "xlwings",
  "pyinstaller>=6.18.0",
  "streamlit-desktop-app>=0.3.4",
  "python-calamine>=0.6.2",
  "fastapi>=0.115.0",
  "uvicorn[standard]",
]

[project.optional-dependencies]
pdf = ["weasyprint"]

[tool.hatch.build.targets.wheel]
include = ["config"]

[tool.uv]
package = true
constraint-dependencies = []
