POST http://127.0.0.1:8000/calculate-electricity-benefit-with-valuestreams
Content-Type: application/json

{
  "utility": "PGE",
  "region": "CZ12",
  "start_datetime": "2021-10-01 00:00:00",
  "end_datetime": "2033-10-01 00:00:00",
  "project_id": "MAR101421",
  "units": 1.0,
  "ntg": 0.95,
  "mwh_savings": 12.434473,
  "load_shape_name": "NONRES_INDOOR_CFL_LTG",
  "discount": 0.85,
  "value_streams": ["energy", "ghg_rebalancing", "total"],
  "custom_value_streams": {
    "2021": {
      "1" : {"custom_value_stream_1":  0.1234, "custom_value_stream_2":  1.234},
      "2" : {"custom_value_stream_1":  0.4567, "custom_value_stream_2":  4.567}
    }
  }
}
