POST http://127.0.0.1:8000/calculate-electricity-benefit-with-timeseries
Content-Type: application/json

{
  "utility": "PGE",
  "region": "CZ12",
  "start_datetime": "2021-10-01 00:00:00",
  "end_datetime": "2033-10-01 00:00:00",
  "project_id": "MAR101421",
  "units": 1.0,
  "ntg": 0.95,
  "mwh_savings": 12.434473,
  "load_shape_name": "NONRES_INDOOR_CFL_LTG",
  "discount": {
    "2021": {
      "10": 0.85,
      "11": 0.87
    },
    "2022": {
      "1": 0.88,
      "2": 3
    }
  }
}

###
