gateways:
  local_duckdb:
    connection:
      type: duckdb
      database: {{ env_var('DB') }}
    state_connection:
      type: duckdb
      database: {{ env_var('DB') | replace('.db', '') }}_state_core.db

default_gateway: local_duckdb

model_defaults:
  dialect: duckdb
