MODEL(
  name core_layer0_base.measures,
  kind VIEW,
);

SELECT
    id::VARCHAR AS id,
    program_name::VARCHAR AS program_name,
    label_1::VARCHAR AS label_1,
    label_2::VARCHAR AS label_2,
    label_3::VARCHAR AS label_3,
    label_4::VARCHAR AS label_4,
    label_5::VARCHAR AS label_5,
    measure_id::VARCHAR AS measure_id,
    project_id::VARCHAR AS project_id,
    measure_name::VARCHAR AS measure_name,
    CASE WHEN avoided_cost_subset IS NULL THEN 'System-wide' ELSE avoided_cost_subset END::VARCHAR AS avoided_cost_subset,
    start_year::INT AS start_year,
    start_quarter::INT AS start_quarter,
    COALESCE(m.measure_specific_discount_rate, gp.discount_rate)::FLOAT AS discount_rate,
    measure_unit::VARCHAR AS measure_unit,
    unit_quantity::FLOAT AS unit_quantity,
    estimated_useful_life::INT AS estimated_useful_life,
    net_to_gross_ratio::FLOAT AS net_to_gross_ratio,
    admin_cost_upfront_dollar::FLOAT AS admin_cost_upfront_dollar,
    admin_cost_annual_dollar_per_year::FLOAT AS admin_cost_annual_dollar_per_year,
    utility_direct_investment_in_ders_dollar::FLOAT AS utility_direct_investment_in_ders_dollar,
    credit_and_collection_cost_dollar::FLOAT AS credit_and_collection_cost_dollar,
    utility_incentive_upfront_dollar::FLOAT AS utility_incentive_upfront_dollar,
    utility_incentive_annual_dollar_per_year::FLOAT AS utility_incentive_annual_dollar_per_year,
    incremental_cost_upfront_dollar::FLOAT AS incremental_cost_upfront_dollar,
    incremental_cost_annual_dollar_per_year::FLOAT AS incremental_cost_annual_dollar_per_year,
    host_customer_transaction_cost_dollar::FLOAT AS host_customer_transaction_cost_dollar,
    host_customer_interconnection_cost_dollar::FLOAT AS host_customer_interconnection_cost_dollar,
    host_customer_tax_incentive_upfront_dollar::FLOAT AS host_customer_tax_incentive_upfront_dollar,
    UPPER(electric_savings_load_shape)::VARCHAR AS electric_savings_load_shape,
    annual_electric_savings_kwh::FLOAT AS annual_electric_savings_kwh,
    coincident_peak_savings_kw::FLOAT AS coincident_peak_savings_kw,
    UPPER(natural_gas_savings_load_shape)::VARCHAR AS natural_gas_savings_load_shape,
    annual_natural_gas_savings_mmbtu::FLOAT AS annual_natural_gas_savings_mmbtu,
    annual_propane_savings_mmbtu::FLOAT AS annual_propane_savings_mmbtu,
    annual_oil_savings_mmbtu::FLOAT AS annual_oil_savings_mmbtu,
    annual_wood_savings_mmbtu::FLOAT AS annual_wood_savings_mmbtu,
    annual_diesel_savings_mmbtu::FLOAT AS annual_diesel_savings_mmbtu,
    host_customer_non_energy_impacts_upfront_dollar::FLOAT AS host_customer_non_energy_impacts_upfront_dollar,
    host_customer_non_energy_impacts_low_income_upfront_dollar::FLOAT AS host_customer_non_energy_impacts_low_income_upfront_dollar,
    change_in_host_customer_resilience::FLOAT AS change_in_host_customer_resilience,
    change_in_societal_resilience::FLOAT AS change_in_societal_resilience,
    custom_1_value_stream_name::VARCHAR AS custom_1_value_stream_name,
    custom_1_value_stream_impact_category::VARCHAR AS custom_1_value_stream_impact_category,
    custom_1_annual_savings::FLOAT AS custom_1_annual_savings,
    custom_2_value_stream_name::VARCHAR AS custom_2_value_stream_name,
    custom_2_value_stream_impact_category::VARCHAR AS custom_2_value_stream_impact_category,
    custom_2_annual_savings::FLOAT AS custom_2_annual_savings,
    custom_3_value_stream_name::VARCHAR AS custom_3_value_stream_name,
    custom_3_value_stream_impact_category::VARCHAR AS custom_3_value_stream_impact_category,
    custom_3_annual_savings::FLOAT AS custom_3_annual_savings,
    custom_4_value_stream_name::VARCHAR AS custom_4_value_stream_name,
    custom_4_value_stream_impact_category::VARCHAR AS custom_4_value_stream_impact_category,
    custom_4_annual_savings::FLOAT AS custom_4_annual_savings,
    custom_5_value_stream_name::VARCHAR AS custom_5_value_stream_name,
    custom_5_value_stream_impact_category::VARCHAR AS custom_5_value_stream_impact_category,
    custom_5_annual_savings::FLOAT AS custom_5_annual_savings,
    MAP(
        [
          'ELECTRIC', 
          'NATURAL GAS', 
          'PROPANE', 
          'DIESEL', 
          'OIL',
          'WOOD',
          'HOST CUSTOMER RESILIENCE',
          'HOST CUSTOMER NEIs',
          'HOST CUSTOMER NEIs - LI',
          'SOCIETAL RESILIENCE',
          'UTILITY CREDIT & COLLECTION',
          UPPER(custom_1_value_stream_impact_category), 
          UPPER(custom_2_value_stream_impact_category), 
          UPPER(custom_3_value_stream_impact_category), 
          UPPER(custom_4_value_stream_impact_category), 
          UPPER(custom_5_value_stream_impact_category)
        ], 
        [
          annual_electric_savings_kwh,
          annual_natural_gas_savings_mmbtu,
          annual_propane_savings_mmbtu,
          annual_diesel_savings_mmbtu,
          annual_oil_savings_mmbtu,
          annual_wood_savings_mmbtu,
          change_in_host_customer_resilience,
          host_customer_non_energy_impacts_upfront_dollar,
          host_customer_non_energy_impacts_low_income_upfront_dollar,
          change_in_societal_resilience,
          credit_and_collection_cost_dollar,
          custom_1_annual_savings,
          custom_2_annual_savings,
          custom_3_annual_savings,
          custom_4_annual_savings,
          custom_5_annual_savings
        ]
        )::MAP<VARCHAR, FLOAT> AS energy_savings_by_impact_category,
        [
          'ADMIN',
          'UTILITY INCENTIVE',
          'MEASURE COST',
          'TAX INCENTIVE',
        ]::ARRAY<VARCHAR> AS cost_commodities,
    MAP(
        [
          'admin_cost_upfront_dollar',
          'admin_cost_annual_dollar_per_year',
          'utility_direct_investment_in_ders_dollar',
          'utility_incentive_upfront_dollar',
          'utility_incentive_annual_dollar_per_year',
          'incremental_cost_upfront_dollar',
          'incremental_cost_annual_dollar_per_year',
          'host_customer_transaction_cost_dollar',
          'host_customer_interconnection_cost_dollar',
          'host_customer_tax_incentive_upfront_dollar'
        ],
        [
          admin_cost_upfront_dollar,
          admin_cost_annual_dollar_per_year,
          utility_direct_investment_in_ders_dollar,
          utility_incentive_upfront_dollar,
          utility_incentive_annual_dollar_per_year,
          incremental_cost_upfront_dollar,
          incremental_cost_annual_dollar_per_year,
          host_customer_transaction_cost_dollar,
          host_customer_interconnection_cost_dollar,
          host_customer_tax_incentive_upfront_dollar
        ]
        )::MAP<VARCHAR, FLOAT> AS costs_by_type,
    MAP(
        [
          'ELECTRIC',
          'NATURAL GAS'
        ],
        [
          UPPER(electric_savings_load_shape),
          UPPER(natural_gas_savings_load_shape)
        ]
    )::MAP<VARCHAR, VARCHAR> AS load_shape_mapping_by_impact_category,
FROM 
  openbca_input.measures m, openbca_input.global_parameters gp