MODEL(
  name core_layer0_base.measures,
  kind VIEW,
);

SELECT
    id::VARCHAR AS id,
    measure_id::VARCHAR AS measure_id,
    project_id::VARCHAR AS project_id,
    program_name::VARCHAR AS program_name,
    measure_include::VARCHAR AS measure_include,
    version::VARCHAR AS version,
    CASE WHEN avoided_cost_subset IS NULL THEN 'System-wide' ELSE avoided_cost_subset END::VARCHAR AS avoided_cost_subset,
    start_year::INT AS start_year,
    start_quarter::INT AS start_quarter,
    discount_rate::FLOAT AS discount_rate, 
    measure_name::VARCHAR AS measure_name,
    measure_unit::VARCHAR AS measure_unit,
    unit_quantity::FLOAT AS unit_quantity,
    UPPER(electric_load_shape)::VARCHAR AS electric_load_shape,
    annual_electric_savings_kwh::FLOAT AS annual_electric_savings_kwh,
    coincident_peak_savings_kw::FLOAT AS coincident_peak_savings_kw,
    UPPER(natural_gas_load_shape)::VARCHAR AS natural_gas_load_shape,
    annual_natural_gas_savings_mmbtu::FLOAT AS annual_natural_gas_savings_mmbtu,
    annual_propane_savings_mmbtu::FLOAT AS annual_propane_savings_mmbtu,
    annual_oil_savings_mmbtu::FLOAT AS annual_oil_savings_mmbtu,
    annual_diesel_savings_mmbtu::FLOAT AS annual_diesel_savings_mmbtu,
    estimated_useful_life::INT AS estimated_useful_life,
    ntg::FLOAT AS ntg,
    administration_costs_upfront_dollar_per_unit::FLOAT AS administration_costs_upfront_dollar_per_unit,
    administration_costs_annual_dollar_per_unit_year::FLOAT AS administration_costs_annual_dollar_per_unit_year,
    utility_incentive_upfront_dollar_per_unit::FLOAT AS utility_incentive_upfront_dollar_per_unit,
    utility_incentive_annual_dollar_per_unit_year::FLOAT AS utility_incentive_annual_dollar_per_unit_year,
    incremental_costs_upfront_dollar_per_unit::FLOAT AS incremental_costs_upfront_dollar_per_unit,
    incremental_costs_annual_dollar_per_unit_year::FLOAT AS incremental_costs_annual_dollar_per_unit_year,
    host_customer_transaction_costs_dollar_per_unit::FLOAT AS host_customer_transaction_costs_dollar_per_unit,
    host_customer_interconnection_costs_dollar_per_unit::FLOAT AS host_customer_interconnection_costs_dollar_per_unit,
    host_customer_tax_incentive_upfront_dollar_per_unit::FLOAT AS host_customer_tax_incentive_upfront_dollar_per_unit,
    host_customer_non_energy_impacts_dollar_per_unit::FLOAT AS host_customer_non_energy_impacts_dollar_per_unit,
    host_customer_non_energy_impacts_low_income_dollar_per_unit::FLOAT AS host_customer_non_energy_impacts_low_income_dollar_per_unit,
    change_in_host_customer_risk_dollar_per_unit::FLOAT AS change_in_host_customer_risk_dollar_per_unit,
    change_in_host_customer_reliability_dollar_per_unit::FLOAT AS change_in_host_customer_reliability_dollar_per_unit,
    change_in_host_customer_resilience_dollar_per_unit::FLOAT AS change_in_host_customer_resilience_dollar_per_unit,
    change_in_societal_resilience_dollar_per_unit::FLOAT AS change_in_societal_resilience_dollar_per_unit,
    custom_1_value_stream_name::VARCHAR AS custom_1_value_stream_name,
    custom_1_value_stream_commodity::VARCHAR AS custom_1_value_stream_commodity,
    custom_1_annual_savings::FLOAT AS custom_1_annual_savings, 
    custom_2_value_stream_name::VARCHAR AS custom_2_value_stream_name,
    custom_2_value_stream_commodity::VARCHAR AS custom_2_value_stream_commodity,
    custom_2_annual_savings::FLOAT AS custom_2_annual_savings, 
    custom_3_value_stream_name::VARCHAR AS custom_3_value_stream_name,
    custom_3_value_stream_commodity::VARCHAR AS custom_3_value_stream_commodity,
    custom_3_annual_savings::FLOAT AS custom_3_annual_savings, 
    custom_4_value_stream_name::VARCHAR AS custom_4_value_stream_name,
    custom_4_value_stream_commodity::VARCHAR AS custom_4_value_stream_commodity,
    custom_4_annual_savings::FLOAT AS custom_4_annual_savings, 
    custom_5_value_stream_name::VARCHAR AS custom_5_value_stream_name,
    custom_5_value_stream_commodity::VARCHAR AS custom_5_value_stream_commodity,
    custom_5_annual_savings::FLOAT AS custom_5_annual_savings, 
    label_1::VARCHAR AS label_1,    
    label_2::VARCHAR AS label_2,
    label_3::VARCHAR AS label_3,
    label_4::VARCHAR AS label_4,
    label_5::VARCHAR AS label_5,
    MAP(
        [
          'ELECTRIC', 
          'NATURAL GAS', 
          'PROPANE', 
          'DIESEL', 
          'OIL',
          'HOST CUSTOMER',
          -- 'HOST CUSTOMER RISK',
          -- 'HOST CUSTOMER RELIABILITY', 
          -- 'HOST CUSTOMER RESILIENCE',
          -- 'HOST CUSTOMER NEIs',
          -- 'HOST CUSTOMER NEIs - LI',
          'SOCIETAL',
          UPPER(custom_1_value_stream_commodity), 
          UPPER(custom_2_value_stream_commodity), 
          UPPER(custom_3_value_stream_commodity), 
          UPPER(custom_4_value_stream_commodity), 
          UPPER(custom_5_value_stream_commodity)
        ], 
        [
          annual_electric_savings_kwh, 
          annual_natural_gas_savings_mmbtu, 
          annual_propane_savings_mmbtu, 
          annual_diesel_savings_mmbtu, 
          annual_oil_savings_mmbtu, 
          1.0,
          1.0,
          -- change_in_host_customer_risk_dollar_per_unit,
          -- change_in_host_customer_reliability_dollar_per_unit,
          -- change_in_host_customer_resilience_dollar_per_unit,
          -- host_customer_non_energy_impacts_dollar_per_unit,
          -- host_customer_non_energy_impacts_low_income_dollar_per_unit,
          -- change_in_societal_resilience_dollar_per_unit,
          custom_1_annual_savings, 
          custom_2_annual_savings, 
          custom_3_annual_savings, 
          custom_4_annual_savings, 
          custom_5_annual_savings
          ]
        )::MAP<VARCHAR, FLOAT> AS energy_savings_by_commodity,
        [
          'ADMIN',
          'UTILITY INCENTIVE',
          'MEASURE COST',
          'TAX INCENTIVE',
        ]::ARRAY<VARCHAR> AS cost_commodities,
    MAP(
        [
          'administration_costs_upfront_dollar_per_unit', 
          'administration_costs_annual_dollar_per_unit_year', 
          'utility_incentive_upfront_dollar_per_unit', 
          'utility_incentive_annual_dollar_per_unit_year',
          'incremental_costs_upfront_dollar_per_unit',
          'incremental_costs_annual_dollar_per_unit_year',
          'host_customer_transaction_costs_dollar_per_unit',
          'host_customer_interconnection_costs_dollar_per_unit',
          'host_customer_tax_incentive_upfront_dollar_per_unit'
          --'annual_o_m_cost_per_unit_dollar_per_year'
        ], 
        [
          administration_costs_upfront_dollar_per_unit, 
          administration_costs_annual_dollar_per_unit_year, 
          utility_incentive_upfront_dollar_per_unit, 
          utility_incentive_annual_dollar_per_unit_year,
          incremental_costs_upfront_dollar_per_unit,
          incremental_costs_annual_dollar_per_unit_year,
          host_customer_transaction_costs_dollar_per_unit,
          host_customer_interconnection_costs_dollar_per_unit,
          host_customer_tax_incentive_upfront_dollar_per_unit
          --annual_o_m_cost_per_unit_dollar_per_year
          ]
        )::MAP<VARCHAR, FLOAT> AS costs_by_type,
    MAP(
        [
          'ELECTRIC', 
          'NATURAL GAS'
        ], 
        [
          UPPER(electric_load_shape), 
          UPPER(natural_gas_load_shape)
        ]
      )::MAP<VARCHAR, VARCHAR> AS load_shape_mapping_by_commodity,
FROM 
  openbca_input.measures
