MODEL (
    name openbca_input.measures,
    kind FULL,
);

SELECT
    CAST(unique_row_id AS STRING) AS unique_row_id,
    CAST(measure_id AS STRING) AS measure_id,
    CAST(project_id AS STRING) AS project_id,
    CAST(program_name AS STRING) AS program_name,
    CAST(measure_include AS STRING) AS measure_include,
    CAST(version AS STRING) AS version,
    CAST(avoided_cost_subset AS STRING) AS avoided_cost_subset,
    CAST(start_year AS INT) AS start_year,
    CAST(start_quarter AS INT) AS start_quarter,
    CAST(discount_rate AS FLOAT) AS discount_rate, 
    CAST(measure_name AS STRING) AS measure_name,
    CAST(measure_unit AS STRING) AS measure_unit,
    CAST(unit_quantity AS FLOAT) AS unit_quantity,
    CAST(electric_load_shape AS STRING) AS electric_load_shape,
    CAST(annual_kwh_impact AS FLOAT) AS annual_kwh_savings,
    CAST(coincident_peak_kw_impact AS FLOAT) AS coincident_peak_kw_impact,
    CAST(natural_gas_load_shape AS STRING) AS natural_gas_load_shape,
    CAST(annual_natural_gas_impact_mmbtu as FLOAT) AS annual_natural_gas_mmbtu_savings,
    CAST(annual_other_fuel_propane_mmbtu as FLOAT) AS annual_propane_mmbtu_savings,
    CAST(annual_other_fuel_heating_oil_mmbtu as FLOAT) AS annual_heating_oil_mmbtu_savings,
    CAST(annual_other_fuel_diesel_mmbtu as FLOAT) AS annual_diesel_mmbtu_savings,
    CAST(estimated_useful_life_years AS INT) AS estimated_useful_life,
    CAST(ntg AS FLOAT) AS ntg,
    CAST(incremental_costs_upfront_per_unit_dollar AS FLOAT) AS incremental_costs_upfront_per_unit_dollar,
    CAST(annual_o_m_cost_per_unit_dollar_per_year AS FLOAT) AS annual_o_m_cost_per_unit_dollar_per_year,
    CAST(utility_upfront_incentive_per_unit_dollar AS FLOAT) AS utility_upfront_incentive_per_unit_dollar,
    CAST(utility_annual_incentive_per_unit_dollar_per_year AS FLOAT) AS utility_annual_incentive_per_unit_dollar_per_year,
    CAST(administration_costs_per_unit_dollar AS FLOAT) AS administration_costs_per_unit_dollar,
    CAST(host_customer_transaction_costs_per_unit_dollar AS FLOAT) AS host_customer_transaction_costs_per_unit_dollar,
    CAST(host_customer_interconnection_costs_per_unit_dollar AS FLOAT) AS host_customer_interconnection_costs_per_unit_dollar,
    CAST(host_customer_tax_incentives_per_unit_dollar AS FLOAT) AS host_customer_tax_incentives_per_unit_dollar,
    CAST(host_customer_non_energy_impacts_per_unit_dollar AS FLOAT) AS host_customer_non_energy_impacts_per_unit_dollar,
    CAST(host_customer_non_energy_impacts_low_income_per_unit_dollar AS FLOAT) AS host_customer_non_energy_impacts_low_income_per_unit_dollar,
    CAST(change_in_host_customer_reliability_per_unit AS FLOAT) AS change_in_host_customer_reliability_per_unit,
    CAST(change_in_host_customer_resilience_per_unit AS FLOAT) AS change_in_host_customer_resilience_per_unit,
    CAST(change_in_societal_resilience_per_unit AS FLOAT) AS change_in_societal_resilience_per_unit,
    CAST(custom_v1 AS STRING) AS custom_v1,
    CAST(custom_v2 AS STRING) AS custom_v2, 
    CAST(custom_v3 AS STRING) AS custom_v3,
    CAST(custom_v4 AS STRING) AS custom_v4,
    CAST(custom_v5 AS STRING) AS custom_v5,
    CAST(label_1 AS STRING) AS label_1,    
    CAST(label_2 AS STRING) AS label_2,
    CAST(label_3 AS STRING) AS label_3,
    CAST(label_4 AS STRING) AS label_4,
    CAST(label_5 AS STRING) AS label_5,
--    NULL AS avoided_costs, -- FIXME
FROM nspm.openbca_input_measures
