MODEL (
    name openbca_input.measures,
    kind FULL,
    grain(
        unique_row_id,
        measure_id, 
        project_id, 
        program_name, 
        measure_include, 
        version, 
        subset, 
        start_year, 
        start_quarter, 
        measure_name, 
        measure_unit, 
        unit_quantity, 
        loadshape_mapping, 
        annual_kwh_impact, 
        peak_kw_impact, 
        annual_ng_impact_mmbtu, 
        annual_other_fuels_impact_mmbtu, 
        estimated_useful_life_years, 
        ntg, 
        measure_incremental_costs_per_unit_doller, 
        measure_annual_o_m_cost_per_unit_doller_per_year, 
        measure_one_time_incentive_utility_per_unit_doller_per_year, 
        measure_annual_incentive_utility_per_unit_doller_per_year, 
        administration_costs_doller_per_year, 
        measure_transaction_costs_per_unit_doller_per_year, 
        measure_interconnection_costs_per_unit_doller_per_year, 
        measure_tax_incentives_per_unit_doller_per_year, 
        measure_non_energy_impacts_per_unit_doller_per_year, 
        measure_non_energy_impacts_low_income_per_unit_doller_per_year, 
        change_in_host_customer_reliability_customer_minute_outages_cmo, 
        custom_1_subsector, 
        custom_2_zip_code, 
        custom_3, 
        custom_4, 
        custom_5
    )
);

SELECT
    CAST(unique_row_id AS INT) AS unique_row_id,
    CAST(measure_id AS STRING) AS measure_id,
    CAST(project_id AS STRING) AS project_id,
    CAST(program_name AS STRING) AS program_name,
    CAST(measure_include AS STRING) AS measure_include,
    CAST(version AS STRING) AS version,
    CAST(subset AS STRING) AS avoided_cost_subset,
    CAST(start_year AS INT) AS start_year,
    CAST(start_quarter AS STRING) AS start_quarter,
    CAST(measure_name AS STRING) AS measure_name,
    CAST(measure_unit AS STRING) AS measure_unit,
    CAST(unit_quantity AS FLOAT) AS unit_quantity,
    CAST(loadshape_mapping AS STRING) AS loadshape_mapping, 
    CAST(annual_kwh_impact AS FLOAT) AS annual_kwh_impact,
    CAST(peak_kw_impact AS FLOAT) AS peak_kw_impact,
    CAST(annual_ng_impact_mmbtu AS FLOAT) AS annual_ng_impact_mmbtu,
    CAST(annual_other_fuels_impact_mmbtu AS FLOAT) AS annual_other_fuels_impact_mmbtu,
    CAST(estimated_useful_life_years AS INT) AS estimated_useful_life_years,
    CAST(ntg AS FLOAT) AS ntg,
    CAST(measure_incremental_costs_per_unit_doller AS FLOAT) AS measure_incremental_costs_per_unit_doller,
    CAST(measure_annual_o_m_cost_per_unit_doller_per_year AS FLOAT) AS measure_annual_o_m_cost_per_unit_doller_per_year,
    CAST(measure_one_time_incentive_utility_per_unit_doller_per_year AS FLOAT) AS measure_one_time_incentive_utility_per_unit_doller_per_year,
    CAST(measure_annual_incentive_utility_per_unit_doller_per_year AS FLOAT) AS measure_annual_incentive_utility_per_unit_doller_per_year,
    CAST(administration_costs_doller_per_year AS FLOAT) AS administration_costs_doller_per_year,
    CAST(measure_transaction_costs_per_unit_doller_per_year AS FLOAT) AS measure_transaction_costs_per_unit_doller_per_year,
    CAST(measure_interconnection_costs_per_unit_doller_per_year AS FLOAT) AS measure_interconnection_costs_per_unit_doller_per_year,
    CAST(measure_tax_incentives_per_unit_doller_per_year AS FLOAT) AS measure_tax_incentives_per_unit_doller_per_year,
    CAST(measure_non_energy_impacts_per_unit_doller_per_year AS FLOAT) AS measure_non_energy_impacts_per_unit_doller_per_year,      
    CAST(measure_non_energy_impacts_low_income_per_unit_doller_per_year AS FLOAT) AS measure_non_energy_impacts_low_income_per_unit_doller_per_year,
    CAST(change_in_host_customer_reliability_customer_minute_outages_cmo AS FLOAT)
        AS change_in_host_customer_reliability_customer_minute_outages_cmo,
    CAST(custom_1_subsector AS STRING) AS custom_1_subsector,
    CAST(custom_2_zip_code AS STRING) AS custom_2_zip_code, 
    CAST(custom_3 AS STRING) AS custom_3,
    CAST(custom_4 AS STRING) AS custom_4,
    CAST(custom_5 AS STRING) AS custom_5
FROM nspm.openbca_input_measures