name: Package and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # Build and upload artifacts for each platform to a draft release
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact-suffix: win-x86_64
        #   - os: macos-latest
        #     artifact-suffix: macos-arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install project and dependencies
        run: uv sync --locked --all-extras --dev

      - name: Build package
        run: make build-pyinstaller-package

      - name: Zip package (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path "dist/openbca-app/*" -DestinationPath "dist/openbca-app-${{ matrix.artifact-suffix }}.zip"

      - name: Zip package (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          zip -r "dist/openbca-app-${{ matrix.artifact-suffix }}.zip" dist/openbca-app/*
      
      - name: Upload Zipped App to Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          files: "dist/openbca-app-${{ matrix.artifact-suffix }}.zip"
          fail_on_unmatched_files: true

      - name: Upload Excel Templates to Draft Release
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          files: "demo_input_files/*.xlsm"
          fail_on_unmatched_files: true
  
  # Publish the release after all artifacts have been uploaded
  publish-release:
    name: Finalize and Publish Release
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish Draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          make_latest: true
