name: Run

on:
  push:
      branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - id: build
        name: Build openbca Docker image
        run: |
          make docker-build
      - id: run NSPM
        name: Run openbca in SQLMesh locally
        run: |
          make docker-run-nspm
      - id: run
        name: Test Streamlit App
        run: |
          make test-app
